version: '3.8'

services:
  opentelemetry-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/otel-local-config.yaml"]
    volumes:
      - ./opentelemetry/collector-config.yaml:/otel-local-config.yaml
    networks:
      - app-network
    ports:
      - '4317:4317'  # Porta para OTLP gRPC
      - '4318:4318'  # Porta HTTP para OTLP

  victoria-metrics:
    image: victoriametrics/victoria-metrics:latest
    ports:
      - '8428:8428'  # Porta padrão do VictoriaMetrics
    volumes:
      - victoria-metrics-data:/victoria-metrics-data
    environment:
      - VM_RETENTION_PERIOD=12  # Retenção de dados em meses (ajuste conforme necessário)
    networks:
      - app-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - '16686:16686'   # UI do Jaeger
      - '14250:14250'   # GRPC
      - '14268:14268'   # HTTP
      - '6831:6831/udp' # UDP
      - '6832:6832/udp' # UDP
      - '9411:9411'     # Zipkin HTTP
    command:
      - "--collector.zipkin.host-port=9411"
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3001:3000'
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/custom
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=administrator
      - GF_SECURITY_ADMIN_USER=administrator
    networks:
      - app-network

volumes:
  grafana-data:
  victoria-metrics-data:

networks:
  app-network:
    driver: bridge
